// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AgedParchmentHome.tsx": () => import("../components/mockups/AgedParchmentHome.tsx"),
  "./components/mockups/ElectricStudioHome.tsx": () => import("../components/mockups/ElectricStudioHome.tsx"),
  "./components/mockups/MidnightForestHome.tsx": () => import("../components/mockups/MidnightForestHome.tsx")
};
