//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  about: About;
  aboutConnection: AboutConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  shop: Shop;
  shopConnection: ShopConnection;
  gallery: Gallery;
  galleryConnection: GalleryConnection;
  tutorials: Tutorials;
  tutorialsConnection: TutorialsConnection;
  downloads: Downloads;
  downloadsConnection: DownloadsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryShopArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryShopConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShopFilter>;
};


export type QueryGalleryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
};


export type QueryTutorialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTutorialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TutorialsFilter>;
};


export type QueryDownloadsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDownloadsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DownloadsFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  about?: InputMaybe<AboutFilter>;
  contact?: InputMaybe<ContactFilter>;
  shop?: InputMaybe<ShopFilter>;
  gallery?: InputMaybe<GalleryFilter>;
  tutorials?: InputMaybe<TutorialsFilter>;
  downloads?: InputMaybe<DownloadsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | About | Contact | Shop | Gallery | Tutorials | Downloads | Folder;

export type HomeHero = {
  __typename?: 'HomeHero';
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
};

export type HomeFeaturedSection = {
  __typename?: 'HomeFeaturedSection';
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  viewAllLabel?: Maybe<Scalars['String']['output']>;
};

export type HomeArtistBanner = {
  __typename?: 'HomeArtistBanner';
  badge?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  portraitImage?: Maybe<Scalars['String']['output']>;
};

export type HomeTutorialsSection = {
  __typename?: 'HomeTutorialsSection';
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  browseAllLabel?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  featuredSection?: Maybe<HomeFeaturedSection>;
  artistBanner?: Maybe<HomeArtistBanner>;
  tutorialsSection?: Maybe<HomeTutorialsSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHeroFilter = {
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
};

export type HomeFeaturedSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  viewAllLabel?: InputMaybe<StringFilter>;
};

export type HomeArtistBannerFilter = {
  badge?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  portraitImage?: InputMaybe<ImageFilter>;
};

export type HomeTutorialsSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  browseAllLabel?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  featuredSection?: InputMaybe<HomeFeaturedSectionFilter>;
  artistBanner?: InputMaybe<HomeArtistBannerFilter>;
  tutorialsSection?: InputMaybe<HomeTutorialsSectionFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  pageTitle?: Maybe<Scalars['String']['output']>;
  leadText?: Maybe<Scalars['String']['output']>;
  paragraph1?: Maybe<Scalars['String']['output']>;
  paragraph2?: Maybe<Scalars['String']['output']>;
  skill1Label?: Maybe<Scalars['String']['output']>;
  skill2Label?: Maybe<Scalars['String']['output']>;
  skill3Label?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  leadText?: InputMaybe<StringFilter>;
  paragraph1?: InputMaybe<StringFilter>;
  paragraph2?: InputMaybe<StringFilter>;
  skill1Label?: InputMaybe<StringFilter>;
  skill2Label?: InputMaybe<StringFilter>;
  skill3Label?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageDescription?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageDescription?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Shop = Node & Document & {
  __typename?: 'Shop';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ShopFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageDescription?: InputMaybe<StringFilter>;
};

export type ShopConnectionEdges = {
  __typename?: 'ShopConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Shop>;
};

export type ShopConnection = Connection & {
  __typename?: 'ShopConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ShopConnectionEdges>>>;
};

export type Gallery = Node & Document & {
  __typename?: 'Gallery';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleryFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageDescription?: InputMaybe<StringFilter>;
};

export type GalleryConnectionEdges = {
  __typename?: 'GalleryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Gallery>;
};

export type GalleryConnection = Connection & {
  __typename?: 'GalleryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryConnectionEdges>>>;
};

export type Tutorials = Node & Document & {
  __typename?: 'Tutorials';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageDescription?: Maybe<Scalars['String']['output']>;
  subscribeLabel?: Maybe<Scalars['String']['output']>;
  youtubeUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TutorialsFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageDescription?: InputMaybe<StringFilter>;
  subscribeLabel?: InputMaybe<StringFilter>;
  youtubeUrl?: InputMaybe<StringFilter>;
};

export type TutorialsConnectionEdges = {
  __typename?: 'TutorialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tutorials>;
};

export type TutorialsConnection = Connection & {
  __typename?: 'TutorialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TutorialsConnectionEdges>>>;
};

export type Downloads = Node & Document & {
  __typename?: 'Downloads';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DownloadsFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageDescription?: InputMaybe<StringFilter>;
};

export type DownloadsConnectionEdges = {
  __typename?: 'DownloadsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Downloads>;
};

export type DownloadsConnection = Connection & {
  __typename?: 'DownloadsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DownloadsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateAbout: About;
  createAbout: About;
  updateContact: Contact;
  createContact: Contact;
  updateShop: Shop;
  createShop: Shop;
  updateGallery: Gallery;
  createGallery: Gallery;
  updateTutorials: Tutorials;
  createTutorials: Tutorials;
  updateDownloads: Downloads;
  createDownloads: Downloads;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateShopArgs = {
  relativePath: Scalars['String']['input'];
  params: ShopMutation;
};


export type MutationCreateShopArgs = {
  relativePath: Scalars['String']['input'];
  params: ShopMutation;
};


export type MutationUpdateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationCreateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationUpdateTutorialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TutorialsMutation;
};


export type MutationCreateTutorialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TutorialsMutation;
};


export type MutationUpdateDownloadsArgs = {
  relativePath: Scalars['String']['input'];
  params: DownloadsMutation;
};


export type MutationCreateDownloadsArgs = {
  relativePath: Scalars['String']['input'];
  params: DownloadsMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  contact?: InputMaybe<ContactMutation>;
  shop?: InputMaybe<ShopMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  tutorials?: InputMaybe<TutorialsMutation>;
  downloads?: InputMaybe<DownloadsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  contact?: InputMaybe<ContactMutation>;
  shop?: InputMaybe<ShopMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  tutorials?: InputMaybe<TutorialsMutation>;
  downloads?: InputMaybe<DownloadsMutation>;
};

export type HomeHeroMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
};

export type HomeFeaturedSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  viewAllLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeArtistBannerMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  portraitImage?: InputMaybe<Scalars['String']['input']>;
};

export type HomeTutorialsSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  browseAllLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  featuredSection?: InputMaybe<HomeFeaturedSectionMutation>;
  artistBanner?: InputMaybe<HomeArtistBannerMutation>;
  tutorialsSection?: InputMaybe<HomeTutorialsSectionMutation>;
};

export type AboutMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  leadText?: InputMaybe<Scalars['String']['input']>;
  paragraph1?: InputMaybe<Scalars['String']['input']>;
  paragraph2?: InputMaybe<Scalars['String']['input']>;
  skill1Label?: InputMaybe<Scalars['String']['input']>;
  skill2Label?: InputMaybe<Scalars['String']['input']>;
  skill3Label?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageDescription?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
};

export type ShopMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageDescription?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageDescription?: InputMaybe<Scalars['String']['input']>;
};

export type TutorialsMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageDescription?: InputMaybe<Scalars['String']['input']>;
  subscribeLabel?: InputMaybe<Scalars['String']['input']>;
  youtubeUrl?: InputMaybe<Scalars['String']['input']>;
};

export type DownloadsMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageDescription?: InputMaybe<Scalars['String']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', heading?: string | null, subheading?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, backgroundImage?: string | null } | null, featuredSection?: { __typename: 'HomeFeaturedSection', heading?: string | null, subheading?: string | null, viewAllLabel?: string | null } | null, artistBanner?: { __typename: 'HomeArtistBanner', badge?: string | null, heading?: string | null, bio?: string | null, ctaLabel?: string | null, portraitImage?: string | null } | null, tutorialsSection?: { __typename: 'HomeTutorialsSection', heading?: string | null, subheading?: string | null, browseAllLabel?: string | null } | null };

export type AboutPartsFragment = { __typename: 'About', pageTitle?: string | null, leadText?: string | null, paragraph1?: string | null, paragraph2?: string | null, skill1Label?: string | null, skill2Label?: string | null, skill3Label?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null };

export type ContactPartsFragment = { __typename: 'Contact', pageTitle?: string | null, pageDescription?: string | null, email?: string | null, location?: string | null };

export type ShopPartsFragment = { __typename: 'Shop', pageTitle?: string | null, pageDescription?: string | null };

export type GalleryPartsFragment = { __typename: 'Gallery', pageTitle?: string | null, pageDescription?: string | null };

export type TutorialsPartsFragment = { __typename: 'Tutorials', pageTitle?: string | null, pageDescription?: string | null, subscribeLabel?: string | null, youtubeUrl?: string | null };

export type DownloadsPartsFragment = { __typename: 'Downloads', pageTitle?: string | null, pageDescription?: string | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', heading?: string | null, subheading?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, backgroundImage?: string | null } | null, featuredSection?: { __typename: 'HomeFeaturedSection', heading?: string | null, subheading?: string | null, viewAllLabel?: string | null } | null, artistBanner?: { __typename: 'HomeArtistBanner', badge?: string | null, heading?: string | null, bio?: string | null, ctaLabel?: string | null, portraitImage?: string | null } | null, tutorialsSection?: { __typename: 'HomeTutorialsSection', heading?: string | null, subheading?: string | null, browseAllLabel?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', heading?: string | null, subheading?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, backgroundImage?: string | null } | null, featuredSection?: { __typename: 'HomeFeaturedSection', heading?: string | null, subheading?: string | null, viewAllLabel?: string | null } | null, artistBanner?: { __typename: 'HomeArtistBanner', badge?: string | null, heading?: string | null, bio?: string | null, ctaLabel?: string | null, portraitImage?: string | null } | null, tutorialsSection?: { __typename: 'HomeTutorialsSection', heading?: string | null, subheading?: string | null, browseAllLabel?: string | null } | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, pageTitle?: string | null, leadText?: string | null, paragraph1?: string | null, paragraph2?: string | null, skill1Label?: string | null, skill2Label?: string | null, skill3Label?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, pageTitle?: string | null, leadText?: string | null, paragraph1?: string | null, paragraph2?: string | null, skill1Label?: string | null, skill2Label?: string | null, skill3Label?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, pageTitle?: string | null, pageDescription?: string | null, email?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, pageTitle?: string | null, pageDescription?: string | null, email?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ShopQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ShopQuery = { __typename?: 'Query', shop: { __typename: 'Shop', id: string, pageTitle?: string | null, pageDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ShopConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShopFilter>;
}>;


export type ShopConnectionQuery = { __typename?: 'Query', shopConnection: { __typename?: 'ShopConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ShopConnectionEdges', cursor: string, node?: { __typename: 'Shop', id: string, pageTitle?: string | null, pageDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GalleryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleryQuery = { __typename?: 'Query', gallery: { __typename: 'Gallery', id: string, pageTitle?: string | null, pageDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GalleryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
}>;


export type GalleryConnectionQuery = { __typename?: 'Query', galleryConnection: { __typename?: 'GalleryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleryConnectionEdges', cursor: string, node?: { __typename: 'Gallery', id: string, pageTitle?: string | null, pageDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TutorialsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TutorialsQuery = { __typename?: 'Query', tutorials: { __typename: 'Tutorials', id: string, pageTitle?: string | null, pageDescription?: string | null, subscribeLabel?: string | null, youtubeUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TutorialsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TutorialsFilter>;
}>;


export type TutorialsConnectionQuery = { __typename?: 'Query', tutorialsConnection: { __typename?: 'TutorialsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TutorialsConnectionEdges', cursor: string, node?: { __typename: 'Tutorials', id: string, pageTitle?: string | null, pageDescription?: string | null, subscribeLabel?: string | null, youtubeUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DownloadsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DownloadsQuery = { __typename?: 'Query', downloads: { __typename: 'Downloads', id: string, pageTitle?: string | null, pageDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DownloadsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DownloadsFilter>;
}>;


export type DownloadsConnectionQuery = { __typename?: 'Query', downloadsConnection: { __typename?: 'DownloadsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DownloadsConnectionEdges', cursor: string, node?: { __typename: 'Downloads', id: string, pageTitle?: string | null, pageDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    heading
    subheading
    ctaPrimary
    ctaSecondary
    backgroundImage
  }
  featuredSection {
    __typename
    heading
    subheading
    viewAllLabel
  }
  artistBanner {
    __typename
    badge
    heading
    bio
    ctaLabel
    portraitImage
  }
  tutorialsSection {
    __typename
    heading
    subheading
    browseAllLabel
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  pageTitle
  leadText
  paragraph1
  paragraph2
  skill1Label
  skill2Label
  skill3Label
  ctaPrimary
  ctaSecondary
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  pageTitle
  pageDescription
  email
  location
}
    `;
export const ShopPartsFragmentDoc = gql`
    fragment ShopParts on Shop {
  __typename
  pageTitle
  pageDescription
}
    `;
export const GalleryPartsFragmentDoc = gql`
    fragment GalleryParts on Gallery {
  __typename
  pageTitle
  pageDescription
}
    `;
export const TutorialsPartsFragmentDoc = gql`
    fragment TutorialsParts on Tutorials {
  __typename
  pageTitle
  pageDescription
  subscribeLabel
  youtubeUrl
}
    `;
export const DownloadsPartsFragmentDoc = gql`
    fragment DownloadsParts on Downloads {
  __typename
  pageTitle
  pageDescription
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const ShopDocument = gql`
    query shop($relativePath: String!) {
  shop(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ShopParts
  }
}
    ${ShopPartsFragmentDoc}`;
export const ShopConnectionDocument = gql`
    query shopConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ShopFilter) {
  shopConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ShopParts
      }
    }
  }
}
    ${ShopPartsFragmentDoc}`;
export const GalleryDocument = gql`
    query gallery($relativePath: String!) {
  gallery(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryParts
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GalleryConnectionDocument = gql`
    query galleryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryFilter) {
  galleryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryParts
      }
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export const TutorialsDocument = gql`
    query tutorials($relativePath: String!) {
  tutorials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TutorialsParts
  }
}
    ${TutorialsPartsFragmentDoc}`;
export const TutorialsConnectionDocument = gql`
    query tutorialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TutorialsFilter) {
  tutorialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TutorialsParts
      }
    }
  }
}
    ${TutorialsPartsFragmentDoc}`;
export const DownloadsDocument = gql`
    query downloads($relativePath: String!) {
  downloads(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DownloadsParts
  }
}
    ${DownloadsPartsFragmentDoc}`;
export const DownloadsConnectionDocument = gql`
    query downloadsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DownloadsFilter) {
  downloadsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DownloadsParts
      }
    }
  }
}
    ${DownloadsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    shop(variables: ShopQueryVariables, options?: C): Promise<{data: ShopQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopQueryVariables, query: string}> {
        return requester<{data: ShopQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopQueryVariables, query: string}, ShopQueryVariables>(ShopDocument, variables, options);
      },
    shopConnection(variables?: ShopConnectionQueryVariables, options?: C): Promise<{data: ShopConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopConnectionQueryVariables, query: string}> {
        return requester<{data: ShopConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopConnectionQueryVariables, query: string}, ShopConnectionQueryVariables>(ShopConnectionDocument, variables, options);
      },
    gallery(variables: GalleryQueryVariables, options?: C): Promise<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}> {
        return requester<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}, GalleryQueryVariables>(GalleryDocument, variables, options);
      },
    galleryConnection(variables?: GalleryConnectionQueryVariables, options?: C): Promise<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}, GalleryConnectionQueryVariables>(GalleryConnectionDocument, variables, options);
      },
    tutorials(variables: TutorialsQueryVariables, options?: C): Promise<{data: TutorialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialsQueryVariables, query: string}> {
        return requester<{data: TutorialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialsQueryVariables, query: string}, TutorialsQueryVariables>(TutorialsDocument, variables, options);
      },
    tutorialsConnection(variables?: TutorialsConnectionQueryVariables, options?: C): Promise<{data: TutorialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialsConnectionQueryVariables, query: string}> {
        return requester<{data: TutorialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TutorialsConnectionQueryVariables, query: string}, TutorialsConnectionQueryVariables>(TutorialsConnectionDocument, variables, options);
      },
    downloads(variables: DownloadsQueryVariables, options?: C): Promise<{data: DownloadsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DownloadsQueryVariables, query: string}> {
        return requester<{data: DownloadsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DownloadsQueryVariables, query: string}, DownloadsQueryVariables>(DownloadsDocument, variables, options);
      },
    downloadsConnection(variables?: DownloadsConnectionQueryVariables, options?: C): Promise<{data: DownloadsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DownloadsConnectionQueryVariables, query: string}> {
        return requester<{data: DownloadsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DownloadsConnectionQueryVariables, query: string}, DownloadsConnectionQueryVariables>(DownloadsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  